# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LHIFrcsU6pRGwpdlNYhr5FSvh6tmUR8kb0Z22/4Epfg9c7X/y8wVIspxi9lSACuPxC49AoxD6lf0znBzS4P8v7jKgZaoRoKrZPx3FMGsh5KFRAv+EBwghp4ak58bG3Dq9XMm06XMHBRxLhwBMAtehGRmW2HWn687TdfQuPbje4Gl0EMX993b++bVfUJeI/dduOdIRbw9VHdClQ6l2Dp1iPQ1IsYTmhsd0boksZIF0eYvScQenADCLYCmXyhd3fZ3OdJ8NMkneR13YyUzfNrpMnXiVRlezJdntNTRN5+D0ktqC2O+MpQyqf99mYnmM6QpDijH8/hmET5clVLJi6ojD7Mr6OJAqiOILAP4s0hEXJFpZhPO6uFXRIJJhOjzQdvpscEzYjyNl1FSTnHhcGWytj9ar04gSIGqLzcn+C24EPg0VQK+2K0/GwqXIbfjfhJy7PVhO+3pP6tAreamEeNMrwtiCABEQHPK6cA7L5u7WFqs6825P+FVJMbW8b0vvpbD1+V7M/HhT37eYSHKTUPJZCMiUVPQ29+1O2u4uItmOsRRrJB+XYf1VakwpPYtKofaWGjuIDUzgABaczZNzv9/3pZD2uDWMzDDQFzDOZK39t9vhH8Y83M/hTjBBigQABCxFFYQhDiw48mviqZxM/m7CMeKmdMj3lFPQ8tdSS1Wh/8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
