travis:
  secure:
    BINSTAR_TOKEN: LHIFrcsU6pRGwpdlNYhr5FSvh6tmUR8kb0Z22/4Epfg9c7X/y8wVIspxi9lSACuPxC49AoxD6lf0znBzS4P8v7jKgZaoRoKrZPx3FMGsh5KFRAv+EBwghp4ak58bG3Dq9XMm06XMHBRxLhwBMAtehGRmW2HWn687TdfQuPbje4Gl0EMX993b++bVfUJeI/dduOdIRbw9VHdClQ6l2Dp1iPQ1IsYTmhsd0boksZIF0eYvScQenADCLYCmXyhd3fZ3OdJ8NMkneR13YyUzfNrpMnXiVRlezJdntNTRN5+D0ktqC2O+MpQyqf99mYnmM6QpDijH8/hmET5clVLJi6ojD7Mr6OJAqiOILAP4s0hEXJFpZhPO6uFXRIJJhOjzQdvpscEzYjyNl1FSTnHhcGWytj9ar04gSIGqLzcn+C24EPg0VQK+2K0/GwqXIbfjfhJy7PVhO+3pP6tAreamEeNMrwtiCABEQHPK6cA7L5u7WFqs6825P+FVJMbW8b0vvpbD1+V7M/HhT37eYSHKTUPJZCMiUVPQ29+1O2u4uItmOsRRrJB+XYf1VakwpPYtKofaWGjuIDUzgABaczZNzv9/3pZD2uDWMzDDQFzDOZK39t9vhH8Y83M/hTjBBigQABCxFFYQhDiw48mviqZxM/m7CMeKmdMj3lFPQ8tdSS1Wh/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
