travis:
  secure:
    BINSTAR_TOKEN: MJN333No/B8mrgbotoWL9nOVJUYtzqwMbcMcTggDCfKup71CJQWftW1zZmCNweRHQJhvJwEa95rfK6KBGhlPsD8OdolEV/iPzqEGCPTMOIvoYoCPMKbocylIJeztuO768+OgKuc5y7N9qCnBUbSsaQjBHoGYOWN8qJQYWgsyr3DQqJE1tbeO7y2/bUDvdDnefxo73lwAtN3qT/roJIsNBhvshJhBGWmys0TOJBQY4AlLpjdDXxJCaUf9NkThv1+Pc1N/pzyx9Ky2ravOgfoscM4KQ4MPHrgnUUaP1UandbyhGTZDXfds9vUF9xubXxzwoxqti+IzZWzClzQNfTlJ2OfHGkBowWBYGuXLe2A0ADz4cyemIP914v8mjFEikqQggajcgLxasJcxz481TEzBheAkgXfFQyGEDrTsFnpo4KFSTBX5ww6Jb7s32yoFJkeD0882QkP/a03JVpFyDbx4ADQo6QrQQZ/z0FlDrUID4r1E+PuFvsVqeaHwEPUj6Ww75eRvm9aEtko7vCsaR8O9HMkcqRJxwlEvI6Gn2ejjwRY8rTgG9p6AWOb1rDnuS7B/JwztFcg8oiiw8pukvJ6zkZuuF7HraONU01TXh93ahaj82HjtAttS6Gs8EkU74R/MAEVPgU5hiQx6oGYNzM1FWdfaDaDtr9hczX5Un16yu9I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
