travis:
  secure:
    BINSTAR_TOKEN: L78yMTOUHdaqhmz9EdoBKP969rIwvbWREnVs9t2oCuKWZ0Qz3+uMDjfHDkQ6h+BnXvUv2AW0KXCLx2tQCs0xcAsO+4uzWrtgyRhFY0qlxFuQH954pCt7aUhpfxaidWlOYVMDQRWLYwO0iWzok5xdeM5YkWVQIhD3pwXr9Uhm9jYzncAQ6NjUso1QMyPIGXdn//iEBJxLpQ4LqE3f7pFd9ag89fv43jfO/XigkE9GerVUd4Y8XIdq3xuTViB9qswBYQQ9ccIvJWzIr4YLKea0ezmKpEAHfFk4K2zihJGFD/F7KroF/64ZFPIq/adJydQWq5lZQ4XqraZwfcXRWKBclLPUahjtrWiyVfXTFcGJarqZmC7b2rwWlFkZiDjDtTC5tAAGOYljYQu1AQ/BWANjp7cHg0+XtHjbiLK3xycWQlCBDwC1cOWydExPs13dH7i66HUIbJcNfqz87fVlHRapnGZQdjSJTHPE9Mac51FgKkOJDHPQEVIWdXltqy4l5TIP9X+/dTTObDsSkeQXl/V8goZ6cUFvea+eJQI8dbiZWo0/lTAq1IirxIeDZrXJ2T1wu8MZ2LGh4Z7xrNVye9ZDbeetWe7jubXBr1q+NlREi06wUMklAtPquW1ugrdMqMAvGXt45spHJIlVLruVqPtDpioARyaXgF/F3ke0uSR7cHg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
