travis:
  secure:
    BINSTAR_TOKEN: MqfO3XzxsILTy8Uqkh8lYNBiBh3HQ816FhVsqt29/E7EkSfvbecwmurSq+xq5EPTYf128dnbX0z91+mkLgfm8yvayRo1AgxE1pEB115jZuXuJrizdV2VlYd6+wkUH7RYEOMMKq/WTxo48woRsBpPCKHNXOl3Wg13KEtyhSS72YsPZ+WjL22fS582nMD2cRqujHhiVVemmg4zYWyWx8u0QsLeXEYkQIkbHyp4XAbjv3Gax5N3+jrC+524N4ZJ6RsopbO8RMsL1J7uQp5rcSlnKttt9tRcholFhkOqvIB21faKJTX4lXLjr2mdfnqP+A8Rysqe1RhuyG2Tm8Hkm2srEhqwCEfajRHzYcINf7Ipu1KOM1ReijWrryFOVVcDEP7WeAeEL+Zhb6QToWxSDufuJV6exgpi0+gNbylf4Xql72uant1Pi4WbgSHyxfyXBPbZIRWyfmKwWQT62wqxKUwrPW55WVMSPWQW/k7eyLvT9/500O3s8X2HrlrpRINUzFg3/8xrap0vA5hhjjzZ0uLPQButs9pdghmTl0bDcVZ77TjVqkP/Ej0JQdj7xB/lgmIglIW2ATSMB+Iqgih9zlYVFntKsFfUqE87Gd//p72BkJL8bs06KrvRA8kHrbHJzVSVL14KXAkg0rCXHmHQQqK7q4XVoIiLqgKDDt/ny/YkLc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
